version: "3.8"

services:
  spark-iceberg:
    image: spark-iceberg
    container_name: spark-iceberg
    build: ./spark
    env_file:
      - spark/.env
    entrypoint: [ './entrypoint.sh', 'master' ]
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - '8888:8888'
      - '8080:8080'
      - '7077:7077'
      - '10000:10000'
      - '10001:10001'


  spark-worker:
    container_name: spark-worker
    image: spark-iceberg
    entrypoint: [ './entrypoint.sh', 'worker' ]
    depends_on:
      - spark-iceberg
    env_file:
      - spark/.env
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - '8081:8081'

  spark-history-server:
    container_name: spark-history
    image: spark-iceberg
    entrypoint: [ './entrypoint.sh', 'history' ]
    depends_on:
      - spark-iceberg
    env_file:
      - spark/.env
    volumes:
      - spark-logs:/opt/spark/spark-events
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - '18080:18080'


volumes:
  spark-logs: